
/*Storie Section Display Data*/
var currentSkin = getCurrentSkin();
var stories = new Zuck('stories', {
  backNative: true,
  previousTap: true,
  skin: currentSkin['name'],
  autoFullScreen: currentSkin['params']['autoFullScreen'],
  avatars:  true,
  paginationArrows: true,
  list: currentSkin['params']['list'],
  cubeEffect: currentSkin['params']['cubeEffect'],
  localStorage: true,
  stories: [
    Zuck.buildTimelineItem(
      "Lise", 
      "img/pictures/1.jpg",
      "Lise",
      "",
      timestamp(),
      [
        ["Chill-1", "photo", 3, "img/pictures/1.jpg", "img/pictures/1.jpg", '', false, false, timestamp()],
      ]
    ),
    Zuck.buildTimelineItem(
      "William A",
      "img/pictures/2.jpg",
      "William A",
      "",
      timestamp(),
      [
        ["gorillaz-1", "photo", 0, "img/pictures/1.jpg", "img/pictures/1.jpg", '', false, false, timestamp()],
      ]
    ),
    Zuck.buildTimelineItem(
      "Dr. Myles",
      "img/pictures/3.jpg",
      "Dr. Myles",
      "",
      timestamp(),
      [
        ["Food-1", "photo", 5, "img/pictures/2.jpg", "img/pictures/2.jpg", '', false, false, timestamp()],
      ]
    ),
    Zuck.buildTimelineItem(
      "Dr-Naresh",
      "img/pictures/4.jpg",
      "Dr. Naresh",
      "",
      timestamp(),
      [
        ["starboy-1", "photo", 5, "img/pictures/1.jpg", "img/pictures/2.jpg", '', false, false, timestamp()]
      ]
    ),
    Zuck.buildTimelineItem(
      "Dr-Mark",
      "img/pictures/5.jpg",
      "Dr. Mark",
      "",
      timestamp(),
      [
        ["KFC-1s", "photo", 5, "img/pictures/2.jpg", "img/pictures/4.jpg", '', false, false, timestamp()]
      ]
    ),
    Zuck.buildTimelineItem(
      "Dr-Myles1",
      "img/pictures/6.jpg",
      "Dr. Myless",
      "",
      timestamp(),
      [
        ["riverscuomo", "photo", 10, "img/pictures/6.jpg", "img/pictures/6.jpg", '', false, false, timestamp()]
      ]
    ),
    Zuck.buildTimelineItem(
      "Dr-Corrie",
      "img/pictures/7.jpg",
      "Dr. Corrie",
      "",
      timestamp(),
      [
        ["Food-3", "photo", 5, "img/pictures/7.jpg", "img/pictures/7.jpg", '', false, false, timestamp()]
      ]
    ),
    Zuck.buildTimelineItem(
      "Dr-Abaza",
      "img/pictures/8.jpg",
      "Dr. Abaza",
      "",
      timestamp(),
      [
        ["starboy-4", "photo", 5, "img/pictures/8.jpg", "img/pictures/8.jpg", '', false, false, timestamp()]
      ]
    ),
  ]
});

/*Storie Section For Php by JSON*/
/*{
  id: "<?php echo rand(); ?>",               // story id
  photo: "img/doc/doc1.jpg",            // story photo (or user photo)
  name: "<?php echo"ahmad"; ?>",             // story name (or user name)
  link: "",             // story link (useless on story generated by script)
  lastUpdated: Math.floor(199 / 1000),      // last updated date in unix time format
  seen: false,          // set true if user has opened

  items:[
    {
      id: "<?php echo rand(); ?>",       // item id
      type: "video",     // photo or video
      length: timeduration.duration,    // photo timeout or video length in seconds - uses 3 seconds timeout for images if not set
      src: "img/video.mp4",      // photo or video src
      preview: "",  // optional - item thumbnail to show in the story carousel instead of the story defined image
      link: "",     // a link to click on story
      linkText: "Vist", // link text
      time: Math.floor(1621921222.274),     // optional a date to display with the story item. unix timestamp are converted to "time ago" format
      seen: true   // set true if current user was read,
      //[customKey]: "", //  custom-value
      //[anotherCustomKey]: "" // another-custom-value
    }
  ]
},*/
/*Storie Section Display Data*/